# netlify.toml (repo root)

[build]
base    = "frontend"      # tells Netlify to cd into /frontend
command = "npm run build"
publish = "frontend/dist"

[[redirects]]
from = "/*"
to   = "/index.html"
status = 200
