# Production Profile Configuration
server:
  port: ${PORT:8080}

spring:
  # Spring Boot will auto-configure datasource from DATABASE_URL environment variable
  datasource:
    properties:
      sslmode: require
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Update schema, create tables if they don't exist
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  
  
  h2:
    console:
      enabled: false # Disable H2 console in production

# Production JWT settings
security:
  jwt:
    secret: ${JWT_SECRET} # Must be set as environment variable
    expiration: 86400000 # 24 hours

logging:
  level:
    com.chesscoach: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN