# Production Profile Configuration
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Only update, don't recreate tables
    show-sql: false
  
  
  h2:
    console:
      enabled: false # Disable H2 console in production

# Production JWT settings
security:
  jwt:
    secret: ${JWT_SECRET} # Must be set as environment variable
    expiration: 86400000 # 24 hours

logging:
  level:
    com.chesscoach: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN