spring:
  application:
    name: chess-coach-backend
  
  # Allow circular references (temporary fix)
  main:
    allow-circular-references: true
  
  # Default to development profile
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Database Configuration (will be overridden by profiles)
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:aVerySecureRandomSecretKeyThatShouldBeChangedInProduction1234567890ABCDEF}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds (configurable)

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.chesscoach: DEBUG
    org.springframework.security: DEBUG