# Production Profile Configuration
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Validate schema matches entities
    show-sql: false
  
  
  h2:
    console:
      enabled: false # Disable H2 console in production

# Production JWT settings
security:
  jwt:
    secret: ${JWT_SECRET} # Must be set as environment variable
    expiration: 86400000 # 24 hours

logging:
  level:
    com.chesscoach: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN